### ISSUE TITLE
代理数据源为ctx.request.body报错

### ISSUE THREAD

**Issue by jane-** [laomu1988/koa2-proxy#2]
原 ctx.request.body 为  {id:0,products:[{id:1},{id:2}]}  这样的时候报错

**Comment by jane-** [comment]
proxy.when(/api(.*)/, function(ctx) {
  var url = ctx.request.url;
  ctx.request.host = 'www.appollo.h5.me:8081';
  ctx.request.path="/api/"
  ctx.request.body= {id:0,products:[{id:1},{id:2}]}
  ctx.request.querystring="url=https://ceshi.api.vipsouq.net"+url
  console.log(ctx,"***99999*****", ctx.request.body);
});

**Comment by laomu1988** [comment]
我这边提示错误：
```
middleware load data error:  Error: getaddrinfo ENOTFOUND www.appollo.h5.me www.appollo.h5.me:8081 Error: getaddrinfo ENOTFOUND www.appollo.h5.me www.appollo.h5.me:8081
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
```

你使用request.host并且没有更改response状态， 这表示是发送给第三方的请求。。 这个错误提示未找到第三方地址， 不清楚你那里的错误提示是怎样的。。 

假如要发给第三方网站且请求中带有body数据，请添加ctx.request.method = 'post';
假如只是作为服务器发送给浏览器， 请使用ctx.response.body,   response才表示服务器的响应。。

**Comment by jane-** [comment]
我这个是本地的服务，这个并没有走到代理的服务里面，本地直接响应404啦
load_remote: http://www.appollo.h5.me:8081/api/?url=https://ceshi.api.vipsouq.net/api/gate/v1/order/create/prepare                
TypeError: source.on is not a function
    at Function.DelayedStream.create (/Users/admin/koa2/koa2-note-master/demo/project/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/Users/admin/koa2/koa2-note-master/demo/project/node_modules/combined-stream/lib/combined_stream.js:43:37)
    at FormData.append (/Users/admin/koa2/koa2-note-master/demo/project/node_modules/form-data/lib/form_data.js:68:3)
    at appendFormValue (/Users/admin/koa2/koa2-note-master/demo/project/node_modules/request/request.js:326:21)
    at Request.init (/Users/admin/koa2/koa2-note-master/demo/project/node_modules/request/request.js:334:13)
    at new Request (/Users/admin/koa2/koa2-note-master/demo/project/node_modules/request/request.js:130:8)
    at request (/Users/admin/koa2/koa2-note-master/demo/project/node_modules/request/index.js:54:10)
    at /Users/admin/koa2/koa2-note-master/demo/project/node_modules/koa2-proxy/lib/middleware/load.js:77:13
    at Promise (<anonymous>)
    at /Users/admin/koa2/koa2-note-master/demo/project/node_modules/koa2-proxy/lib/middleware/load.js:75:16
    at dispatch (/Users/admin/koa2/koa2-note-master/demo/project/node_modules/koa-compose/index.js:42:32)
    at next (/Users/admin/koa2/koa2-note-master/demo/project/node_modules/koa-compose/index.js:43:18)
    at _callee3$ (/Users/admin/koa2/koa2-note-master/demo/project/node_modules/koa2-match/lib/index.js:277:22)
    at tryCatch (/Users/admin/koa2/koa2-note-master/demo/project/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/admin/koa2/koa2-note-master/demo/project/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/admin/koa2/koa2-note-master/demo/project/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/admin/koa2/koa2-note-master/demo/project/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/admin/koa2/koa2-note-master/demo/project/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

**Comment by jane-** [comment]
ctx.request.body= {} body是这样的格式是正常响应的， 但是变成 {products:[{id:1},{id:2}]}  对象里面有对象， 就抛404的

**Comment by jane-** [comment]
我感觉是传不到 {products:[{id:1},{id:2}]}这样的格式一样

**Comment by laomu1988** [comment]
我这边使用mac，
node 6.0.0
koa2-proxy:1.1.3
request: 2.81.0
你那边具体版本号是多少? 试着升级下看看

**Comment by laomu1988** [comment]
我这边测试的时候，直接使用get请求测试的，没有使用post请求。。假如你测试的时候发送请求的header的content-type带有form-data，才会使用form-data模块进行处理, 这时body中数据应该是form-data格式， {key1: value1, key2: value2}, 每个value只能是字符串、数字，或者null， 不能是object对象。
